package io.hydrolix.ketchup.model.hdx

import io.hydrolix.ketchup.model.TimeResolution
import io.hydrolix.ketchup.util.JSON

object HydrolixHitsMapper {
    val transform = Transform(
        "clickhouse_sample_data.hits",
        null,
        TransformType.json,
        "clickhouse_sample_data.hits",
        TransformSettings(
            true,
            TransformCompression.gzip,
            null,
            null,
            JsonFormatDetails(JsonFlattening(false, null, null, null)),
            listOf(
                OutputColumn("WatchID", null, OutputColumnDatatype(HdxValueType.int64, false)),
                OutputColumn("JavaEnable", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("Title", null, OutputColumnDatatype(HdxValueType.string, false)),
                OutputColumn("GoodEvent", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("EventTime", null, OutputColumnDatatype(HdxValueType.datetime64, true, format = "2006-01-02 15:04:05", resolution = TimeResolution.s)),
                OutputColumn("EventDate", null, OutputColumnDatatype(HdxValueType.datetime, false, format = "2006-01-02")),
                OutputColumn("CounterID", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("ClientIP", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("RegionID", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("UserID", null, OutputColumnDatatype(HdxValueType.int64, false)),
                OutputColumn("CounterClass", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("OS", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("UserAgent", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("URL", null, OutputColumnDatatype(HdxValueType.string, false)),
                OutputColumn("Referer", null, OutputColumnDatatype(HdxValueType.string, false)),
                OutputColumn("IsRefresh", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("RefererCategoryID", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("RefererRegionID", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("URLCategoryID", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("URLRegionID", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("ResolutionWidth", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("ResolutionHeight", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("ResolutionDepth", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("FlashMajor", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("FlashMinor", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("FlashMinor2", null, OutputColumnDatatype(HdxValueType.string, false)),
                OutputColumn("NetMajor", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("NetMinor", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("UserAgentMajor", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("UserAgentMinor", null, OutputColumnDatatype(HdxValueType.string, false)),
                OutputColumn("CookieEnable", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("JavascriptEnable", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("IsMobile", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("MobilePhone", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("MobilePhoneModel", null, OutputColumnDatatype(HdxValueType.string, false)),
                OutputColumn("Params", null, OutputColumnDatatype(HdxValueType.string, false)),
                OutputColumn("IPNetworkID", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("TrafficSourceID", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("SearchEngineID", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("SearchPhrase", null, OutputColumnDatatype(HdxValueType.string, false)),
                OutputColumn("AdvEngineID", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("IsArtificial", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("WindowClientWidth", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("WindowClientHeight", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("ClientTimeZone", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("ClientEventTime", null, OutputColumnDatatype(HdxValueType.datetime64, false, format = "2006-01-02 15:04:05", resolution = TimeResolution.s)),
                OutputColumn("SilverlightVersion1", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("SilverlightVersion2", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("SilverlightVersion3", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("SilverlightVersion4", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("PageCharset", null, OutputColumnDatatype(HdxValueType.string, false)),
                OutputColumn("CodeVersion", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("IsLink", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("IsDownload", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("IsNotBounce", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("FUniqID", null, OutputColumnDatatype(HdxValueType.int64, false)),
                OutputColumn("OriginalURL", null, OutputColumnDatatype(HdxValueType.string, false)),
                OutputColumn("HID", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("IsOldCounter", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("IsEvent", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("IsParameter", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("DontCountHits", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("WithHash", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("HitColor", null, OutputColumnDatatype(HdxValueType.string, false)),
                OutputColumn("LocalEventTime", null, OutputColumnDatatype(HdxValueType.datetime64, false, format = "2006-01-02 15:04:05", resolution = TimeResolution.s)),
                OutputColumn("Age", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("Sex", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("Income", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("Interests", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("Robotness", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("RemoteIP", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("WindowName", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("OpenerName", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("HistoryLength", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("BrowserLanguage", null, OutputColumnDatatype(HdxValueType.string, false)),
                OutputColumn("BrowserCountry", null, OutputColumnDatatype(HdxValueType.string, false)),
                OutputColumn("SocialNetwork", null, OutputColumnDatatype(HdxValueType.string, false)),
                OutputColumn("SocialAction", null, OutputColumnDatatype(HdxValueType.string, false)),
                OutputColumn("HTTPError", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("SendTiming", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("DNSTiming", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("ConnectTiming", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("ResponseStartTiming", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("ResponseEndTiming", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("FetchTiming", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("SocialSourceNetworkID", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("SocialSourcePage", null, OutputColumnDatatype(HdxValueType.string, false)),
                OutputColumn("ParamPrice", null, OutputColumnDatatype(HdxValueType.int64, false)),
                OutputColumn("ParamOrderID", null, OutputColumnDatatype(HdxValueType.string, false)),
                OutputColumn("ParamCurrency", null, OutputColumnDatatype(HdxValueType.string, false)),
                OutputColumn("ParamCurrencyID", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("OpenstatServiceName", null, OutputColumnDatatype(HdxValueType.string, false)),
                OutputColumn("OpenstatCampaignID", null, OutputColumnDatatype(HdxValueType.string, false)),
                OutputColumn("OpenstatAdID", null, OutputColumnDatatype(HdxValueType.string, false)),
                OutputColumn("OpenstatSourceID", null, OutputColumnDatatype(HdxValueType.string, false)),
                OutputColumn("UTMSource", null, OutputColumnDatatype(HdxValueType.string, false)),
                OutputColumn("UTMMedium", null, OutputColumnDatatype(HdxValueType.string, false)),
                OutputColumn("UTMCampaign", null, OutputColumnDatatype(HdxValueType.string, false)),
                OutputColumn("UTMContent", null, OutputColumnDatatype(HdxValueType.string, false)),
                OutputColumn("UTMTerm", null, OutputColumnDatatype(HdxValueType.string, false)),
                OutputColumn("FromTag", null, OutputColumnDatatype(HdxValueType.string, false)),
                OutputColumn("HasGCLID", null, OutputColumnDatatype(HdxValueType.int32, false)),
                OutputColumn("RefererHash", null, OutputColumnDatatype(HdxValueType.int64, false)),
                OutputColumn("URLHash", null, OutputColumnDatatype(HdxValueType.int64, false)),
                OutputColumn("CLID", null, OutputColumnDatatype(HdxValueType.int32, false)),
            )
        )
    )

    @JvmStatic
    fun main(args: Array<String>) {
        println(JSON.objectMapper.writerWithDefaultPrettyPrinter().writeValueAsString(transform))
    }
}